# Generated by Django 5.2.6 on 2025-09-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flightcrew",
            options={"verbose_name_plural": "flight_crew"},
        ),
    ]
