# Generated by Django 5.2.6 on 2025-09-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_alter_flightcrew_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flightcrew",
            options={"verbose_name_plural": "Flight crew"},
        ),
    ]
