# Generated by Django 5.2.6 on 2025-09-16 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_flightcrew_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flightcrew",
            options={"verbose_name_plural": "flight crew"},
        ),
        migrations.RemoveField(
            model_name="order",
            name="tickets",
        ),
        migrations.AddField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="airport.order",
            ),
            preserve_default=False,
        ),
    ]
